/// <reference types="Cypress"/>

export default {
// Seletores automação de login
url: 'http://dev1.ssp.ba.intranet/alerta/',
botaoAcessar: '.edge',
campoCpfEmailLogin: '//span[1]/div/div/div[1]/div/input',
campoSenhaLogin: '#input-104',
botaoEntrarLogin: '.large > .v-btn__content',
botaoCadastrarNovoObjeto: '.col-auto > .v-btn > .v-btn__content',
popupLoginOuSenhaInvalidos: '.swal2-popup',
botaoEntrarLoginDesativado: '.large',
botaoXLogin: '.col-auto > .v-btn',
textoHome: '.text-body-1',
cadastreAgoraLogin: '.font-weight-bold',
botaoSairLogout: '.edge',
tituloTelaLogin: 'h2.py-2',
botaoEsqueceuSenhaLogin: '.esqueceu-senha > .v-btn > .v-btn__content',
tituloTelaEsqueceuSenha: '.py-2',
campoCpfEmailRecuperacaoSenha: '.v-text-field__slot',
botaoRecuperarSenha: '.large',
// Seletores automação cadastro de usuário
tituloTelaCadastro: 'h2.py-2',
campoNomeCadastro: '#name',
campoCpfCadastro: '#cpf',
campoMaeCadastro: '#nomeMae',
campoPaiCadastro: '#nomePai',
campoDtNascimentoCadastro: '#dataNascimento',
botaoCancelarCalendarioCadastro: '.v-picker__actions > :nth-child(2)',
botaoOkCalendarioCadastro: '.v-picker__actions > :nth-child(3) > .v-btn__content',
campoEstadoResidenciaCadastro: '#estado',
dropDownEstadoResidenciaCadastro: '.menuable__content__active',
dropDownBahiaResidenciaCadastro: '#list-item-185-4',
campoCidadeResidenciaCadastro: '#cidade',
dropDownCidadeResidenciaCadastro: '.menuable__content__active',
dropDownSalvadorCidadeResidenciaCadastro: '#list-item-208-0 > .v-list-item__content',
campoNacionalidadeCadastro: '.v-select__selections',
estrangeiroDropDownNacionalidade: '#list-item-168-1 > .v-list-item__content',
estrangeiroDropdownNacionalidade2: '//div[5]/div/div[2]',
campoPassaporteCadastro: '#passaporte',
campoEstadoCadastroEstrangeiro: '#estado',
dropDownBahiaCadastroEstrangeiro: '#list-item-173-4 > .v-list-item__content',
dropDownEstadoCadastroEstrangeiro: '.menuable__content__active',
campoCidadeCadastroEstrangeiro: '#cidade',
dropDownCidadeCadastroEstrangeiro: '.menuable__content__active',
dropDownSalvadorCadastroEstrangeiro: '#list-158',
mensagemCampoObrigatorioNome: ':nth-child(2) > .v-input > .v-input__control > .v-text-field__details > .v-messages > .v-messages__wrapper > .v-messages__message',
mensagemCampoObrigatorioCpf: '.v-messages__message',
mensagemCampoObrigatorioMae: '.v-messages__message',
mensagemCampoObrigatorioPassaporte: '.v-messages__message',
botaoAvancarDesativadoCadastro: '.ml-4',
botaoAvancarAtivadoCadastro: '.large',
botaoEntreLogin: '.text-contrast-3',
botaoXcadastro: '.col-auto > .v-btn',
campoEmailCadastro: ':nth-child(1) > .v-input > .v-input__control > .v-input__slot',
campoConfirmarEmailCadastro: ':nth-child(2) > .v-input > .v-input__control > .v-input__slot > .v-text-field__slot',
campoTelefoneCadastro: '#telefoneFixo',
campoCelularCadastro: '#telefoneMovel',
campoSenhaAcessoCadastro: '#senha',
campoConfirmarSenhaCadastro: '#confSenha',
caixaConcordarTermosCadastro: '.v-input--selection-controls__ripple',
botaoConcluirCadastro: '.large',
mensagemCadastroComSucesso: '.swal2-popup',
botaoOkCadastroComSucesso: '.swal2-confirm',
mensagemCpfJaCadastrado: 'li',
mensagemEmailJaCadastrado: 'li',
// Seletores automação consulta de objeto
lupaConsultaObjeto: '.v-input__append-inner > .v-icon',
mensagemCampoObrigatorioConsultaObjeto: '.v-messages__message',
exclamacaoConsultaObjeto: '.object-search > .v-btn.primary--text > .v-btn__content > .v-icon',
infoConsultaObjeto: '.v-card > .v-card__title',
botaoSairInfoConsultaObjeto: '.v-dialog > .v-card > .v-card__actions > .v-btn',
tituloCampoConsultaObjeto: '.h4',
campoConsultaBicicleta: '#input-159',
campoConsultaCelular: '//div[2]/span/div/div/div[1]/div[1]/input',
campoConsultaVeiculo: '//div[2]/span/div/div/div[1]/div[1]/input',
popupSituacaoObjeto: '.text-subtitle-1',
caixaSelecaoTipoObjeto: '.col-4 > span > .v-input > .v-input__control > .v-input__slot',
celularDropDownTipoObjeto: '/html/body/div/div/div/div[2]/div/div[3]',
veiculoDropDownTipoObjeto: '//body/div/div/div/div[2]/div/div[2]/div',
botaoSubirTela: '.v-btn--bottom',
// Seletores automação cadastro de objeto
campoTipoObjetoCadastro: '.v-select__selections',
dropDownTipoBicicletaCadastro: '/html/body/div/div/div/div[2]/div/div[1]',
dropDownTipoCelularCadastro: '/html/body/div/div/div/div[2]/div/div[3]',
dropDownMarcaCelularCadastro: '.v-menu__content',
botaoIniciarCadastro: '.pl-4',
campoMarcaCadastroBicicleta: '/html/body/div/div/div/div/main/div/div/div/div[3]/span/form/span[1]/div/div/div/div/div[1]/div',
campoModeloCadastroBicicleta: '#modelo',
campoCorCadastroBicicleta: '#cor',
campoNumeroSerieCadastroBicicleta: '#numeroSerie',
campoObservacaoCadastroBicicleta: '#observacoes',
botaoCadastrarTelaCadastroObjeto: '.rightSide > .v-btn',
mensagemBicicletaRegistradaSucesso: '#swal2-title',
botaoAgoraNaoDownloadQrcode: '.swal2-cancel',
telaInicialObjetosCadastrados: '.v-main__wrap > .container',
campoMarcaCadastroCelular: '/html/body/div/div/div/div/main/div/div/div/div[3]/span/form/div[1]/div/span/div/div/div[1]/div[1]',
campoModeloCadastroCelular: '#modelo',
campoDescricaoCadastroCelular: '/html/body/div/div/div/div[1]/main/div/div/div/div[3]/span/form/div[6]/div/span/div/div/div[1]/div[1]',
campoImeiCadastroCelular: '/html/body/div/div/div/div/main/div/div/div/div[3]/span/form/div[3]/div[1]/span/div/div/div[1]/div[1]',
mensagemCelularCadastradoSucesso: '#swal2-title',
botaoOkCelularCadastradoSucesso: '.swal2-confirm',
botaoExcluirObjeto: ':nth-child(2) > .rounded-xl',
botaoConfirmarExclusaoObjeto: '.swal2-confirm',
mensagemObjetoExcluidoSucesso: '.swal2-popup',
// Seletores automação alerta de objeto
botaoAlertarObjeto: '.row > :nth-child(1) > .white--text',
campoInformeCidadeAlerta: ':nth-child(3) > :nth-child(4) > :nth-child(1) > :nth-child(1) > .col > .v-input > .v-input__control > .v-input__slot',
itemListaCidadeAlerta: '.v-list-item__content',
campoLogradouroAlerta: '.col-10 > .v-input > .v-input__control > .v-input__slot > .v-select__slot',
botaoConfirmarAlerta: '.row > :nth-child(1) > .white--text',
modalAlertaGeradoSucesso: '.swal2-popup',
botaoOkAlertaGerado: '.swal2-confirm',
situacaoObjeto: '.col > .v-alert > .v-alert__wrapper > .v-alert__content',
botaoRemoverAlerta: '.row > :nth-child(1) > .white--text',
botaoSimRemoverAlerta: '.swal2-confirm',
modalAlertaRemovido: '.swal2-popup',
botaoOkAlertaRemovido: '.swal2-confirm',
dropDownLogradouroAlerta: '.menuable__content__active'
}